html := "films/" . identifier . "/" . identifier . "_clips.html"
file := FileOpen(html,"w")
file.Write("<p>`n")
file.Write("`t<strong>Film: ")
file.Write(title)
file.Write("</strong><br />`n")
file.Write("`t<strong>Date Digitized: ")
file.Write(date_digital)
file.Write("</strong><br />`n")
file.Write("`t<strong>Contents:</strong>`n</p>`n<ul>`n")

iterations := Film.clips.MaxIndex()
li1 = <a href=`"javascript:void`(0`)`;`" onclick=`"jwplayer`(myElement`).seek`(
li2 = `)`">
li3 = </a> Date:
li4 = &`#59`; `(
li5 = `)&`#59`;
li6 = &`#59`;
Loop, %iterations%
{
	file.Write("`t<li>")
	file.Write(li1)
	if A_Index = 1
	{
		file.Write(Film.clips.1.timestamp)
		file.Write(li2)
		file.Write(Film.clips.1.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.1.date)
		file.Write(li4)
		file.Write(Film.clips.1.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.1.video)
		file.Write(", ")
		file.Write(Film.clips.1.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.1.about)
	}
	else if A_Index = 2
	{
		file.Write(Film.clips.2.timestamp)
		file.Write(li2)
		file.Write(Film.clips.2.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.2.date)
		file.Write(li4)
		file.Write(Film.clips.2.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.2.video)
		file.Write(", ")
		file.Write(Film.clips.2.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.2.about)
	}
	else if A_Index = 3
	{
		file.Write(Film.clips.3.timestamp)
		file.Write(li2)
		file.Write(Film.clips.3.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.3.date)
		file.Write(li4)
		file.Write(Film.clips.3.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.3.video)
		file.Write(", ")
		file.Write(Film.clips.3.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.3.about)
	}
	else if A_Index = 4
	{
		file.Write(Film.clips.4.timestamp)
		file.Write(li2)
		file.Write(Film.clips.4.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.4.date)
		file.Write(li4)
		file.Write(Film.clips.4.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.4.video)
		file.Write(", ")
		file.Write(Film.clips.4.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.4.about)
	}
	else if A_Index = 5
	{
		file.Write(Film.clips.5.timestamp)
		file.Write(li2)
		file.Write(Film.clips.5.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.5.date)
		file.Write(li4)
		file.Write(Film.clips.5.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.5.video)
		file.Write(", ")
		file.Write(Film.clips.5.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.5.about)
	}
	else if A_Index = 6
	{
		file.Write(Film.clips.6.timestamp)
		file.Write(li2)
		file.Write(Film.clips.6.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.6.date)
		file.Write(li4)
		file.Write(Film.clips.6.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.6.video)
		file.Write(", ")
		file.Write(Film.clips.6.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.6.about)
	}
	else if A_Index = 7
	{
		file.Write(Film.clips.7.timestamp)
		file.Write(li2)
		file.Write(Film.clips.7.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.7.date)
		file.Write(li4)
		file.Write(Film.clips.7.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.7.video)
		file.Write(", ")
		file.Write(Film.clips.7.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.7.about)
	}
	else if A_Index = 8
	{
		file.Write(Film.clips.8.timestamp)
		file.Write(li2)
		file.Write(Film.clips.8.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.8.date)
		file.Write(li4)
		file.Write(Film.clips.8.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.8.video)
		file.Write(", ")
		file.Write(Film.clips.8.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.8.about)
	}
	else if A_Index = 9
	{
		file.Write(Film.clips.9.timestamp)
		file.Write(li2)
		file.Write(Film.clips.9.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.9.date)
		file.Write(li4)
		file.Write(Film.clips.9.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.9.video)
		file.Write(", ")
		file.Write(Film.clips.9.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.9.about)
	}
	else if A_Index = 10
	{
		file.Write(Film.clips.10.timestamp)
		file.Write(li2)
		file.Write(Film.clips.10.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.10.date)
		file.Write(li4)
		file.Write(Film.clips.10.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.10.video)
		file.Write(", ")
		file.Write(Film.clips.10.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.10.about)
	}
	else if A_Index = 11
	{
		file.Write(Film.clips.11.timestamp)
		file.Write(li2)
		file.Write(Film.clips.11.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.11.date)
		file.Write(li4)
		file.Write(Film.clips.11.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.11.video)
		file.Write(", ")
		file.Write(Film.clips.11.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.11.about)
	}
	else if A_Index = 12
	{
		file.Write(Film.clips.12.timestamp)
		file.Write(li2)
		file.Write(Film.clips.12.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.12.date)
		file.Write(li4)
		file.Write(Film.clips.12.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.12.video)
		file.Write(", ")
		file.Write(Film.clips.12.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.12.about)
	}
	else if A_Index = 13
	{
		file.Write(Film.clips.13.timestamp)
		file.Write(li2)
		file.Write(Film.clips.13.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.13.date)
		file.Write(li4)
		file.Write(Film.clips.13.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.13.video)
		file.Write(", ")
		file.Write(Film.clips.13.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.13.about)
	}
	else if A_Index = 14
	{
		file.Write(Film.clips.14.timestamp)
		file.Write(li2)
		file.Write(Film.clips.14.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.14.date)
		file.Write(li4)
		file.Write(Film.clips.14.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.14.video)
		file.Write(", ")
		file.Write(Film.clips.14.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.14.about)
	}
	else if A_Index = 15
	{
		file.Write(Film.clips.15.timestamp)
		file.Write(li2)
		file.Write(Film.clips.15.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.15.date)
		file.Write(li4)
		file.Write(Film.clips.15.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.15.video)
		file.Write(", ")
		file.Write(Film.clips.15.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.15.about)
	}
	else if A_Index = 16
	{
		file.Write(Film.clips.16.timestamp)
		file.Write(li2)
		file.Write(Film.clips.16.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.16.date)
		file.Write(li4)
		file.Write(Film.clips.16.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.16.video)
		file.Write(", ")
		file.Write(Film.clips.16.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.16.about)
	}
	else if A_Index = 17
	{
		file.Write(Film.clips.17.timestamp)
		file.Write(li2)
		file.Write(Film.clips.17.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.17.date)
		file.Write(li4)
		file.Write(Film.clips.17.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.17.video)
		file.Write(", ")
		file.Write(Film.clips.17.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.17.about)
	}
	else if A_Index = 18
	{
		file.Write(Film.clips.18.timestamp)
		file.Write(li2)
		file.Write(Film.clips.18.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.18.date)
		file.Write(li4)
		file.Write(Film.clips.18.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.18.video)
		file.Write(", ")
		file.Write(Film.clips.18.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.18.about)
	}
	else if A_Index = 19
	{
		file.Write(Film.clips.19.timestamp)
		file.Write(li2)
		file.Write(Film.clips.19.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.19.date)
		file.Write(li4)
		file.Write(Film.clips.19.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.19.video)
		file.Write(", ")
		file.Write(Film.clips.19.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.19.about)
	}
	else if A_Index = 20
	{
		file.Write(Film.clips.20.timestamp)
		file.Write(li2)
		file.Write(Film.clips.20.name)
		file.Write(li3)
		file.Write(" ")
		file.Write(Film.clips.20.date)
		file.Write(li4)
		file.Write(Film.clips.20.duration)
		file.Write(li5)
		file.Write(" ")
		file.Write(Film.clips.20.video)
		file.Write(", ")
		file.Write(Film.clips.20.audio)
		file.Write(li6)
		file.Write(" ")
		file.Write(Film.clips.20.about)
	}
	else
	{
		MsgBox, Add Clips Index: %A_Index%`nhpl_clips.ahk`n`nApp Exit
		Return
	}
	file.Write("</li>`n")
}

file.Write("</ul>")
file.Close()
